export interface Publication {
  id: string;
  title: string;
  authors: string;
  venue: string;
  year: string;
  doi?: string;
  url?: string;
  citations?: string;
  citationsUrl?: string;
  patentNumber?: string;
}

export const journalArticles: Publication[] = [
  {
    id: "ja-01",
    title: "Sea Urchin Shaped Cobalt Carbonate Hydroxide Hydrate Tribo‐Positive Material for Triboelectric Nanogenerator",
    authors: "A Mannan, M Noman, A Suliman, RA Shaukat, SB Ghode, JK Sawant, ...",
    venue: "Advanced Sustainable Systems 10 (8), e70625",
    year: "2026",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:k_IJM867U9cC",
    citations: "",
  },
  {
    id: "ja-02",
    title: "Human mimetic sensory-interfaced neuromorphic devices and their training mechanism",
    authors: "JK Sawant, SB Ghode, CS Patil, J Kim, A Mannan, M Noman, H Hwang, ...",
    venue: "International Journal of Extreme Manufacturing 8 (3), 032008",
    year: "2026",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:iH-uZ7U-co4C",
    citations: "1",
  },
  {
    id: "ja-03",
    title: "3-dimensional multistate memristor structures based neuromorphic devices for high-density in-memory computing",
    authors: "SB Ghode, CS Patil, JK Sawant, J Kim, MY Chougale, M Noman, ...",
    venue: "Materials Science and Engineering: R: Reports 169, 101184",
    year: "2026",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:bEWYMUwI8FkC",
    citations: "2",
  },
  {
    id: "ja-04",
    title: "High flexible, ultra‐robust piezoelectric nanogenerator based on hexagonal α‐Beryllium Oxide/PVDF composite thin film: E‐skin and energy harvesting applications",
    authors: "CS Patil, J Kim, SB Ghode, MV Paranjape, JK Sawant, M Noman, ...",
    venue: "Advanced Functional Materials 36 (13), e17516",
    year: "2026",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:RHpTSmoSYBkC",
    citations: "12",
  },
  {
    id: "ja-05",
    title: "Fe/Fe3C Embedded Pyrazine‐Based Porous Organic Network for Superior Tribo‐Charge and Electrochemical Double Layer Capacitance",
    authors: "M Noman, QM Saqib, I Ahmad, CS Patil, SR Patil, J Kim, SB Ghode, ...",
    venue: "Advanced Functional Materials 36 (8), e13190",
    year: "2026",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:_Qo2XoVZTnwC",
    citations: "1",
  },
  {
    id: "ja-06",
    title: "Humidity-responsive multistate resistive switching device for non-contact sensory neuro-electronic applications",
    authors: "MY Chougale, SB Ghode, SL Patil, J Kim, GM Lohar, SR Patil, ...",
    venue: "eScience, 100520",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:r0BpntZqJG4C",
    citations: "6",
  },
  {
    id: "ja-07",
    title: "Microspace Triboelectric Nanogenerator Based on Biocompatible Lignin-Derived Activated Carbon for Advanced Active Sensing Applications",
    authors: "J Kim, M Noman, CS Patil, A Muhammad Ajaz, SB Ghode, Y Ko, H Hwang, ...",
    venue: "ACS Applied Materials & Interfaces 17 (47), 65324-65334",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:4JMBOYKVnBMC",
    citations: "4",
  },
  {
    id: "ja-08",
    title: "Unraveling the electrocatalytic properties of non-noble metal-based nickel-cobalt-tungsten/MXene heterocomposite towards trifunctional hydrogen evolution reaction, oxygen …",
    authors: "SR Patil, R Kulkarni, SH Talib, SB Ghode, QM Saqib, M Noman, CS Patil, ...",
    venue: "Journal of Power Sources 652, 237675",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:TQgYirikUcIC",
    citations: "21",
  },
  {
    id: "ja-09",
    title: "Reactivated cathode material from waste alkaline batteries for supercapacitor electrodes: interplay study between pyrolysis temperature and surface morphology",
    authors: "CS Patil, M Noman, SB Ghode, SR Patil, J Kim, QM Saqib, A Samage, ...",
    venue: "Small 21 (33), 2502556",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:R3hNpaxXUhUC",
    citations: "6",
  },
  {
    id: "ja-10",
    title: "Plasma-assisted surface modification and formation of oxygen vacancies in coffee-derived carbon for triboelectric energy harvesting and electrocatalytic water splitting",
    authors: "SB Ghode, CS Patil, J Kim, VP Bhandigare, J Kim, A Mannan, Y Ko, ...",
    venue: "Nano Energy 141, 111116",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:mB3voiENLucC",
    citations: "14",
  },
  {
    id: "ja-11",
    title: "Advances in tribonegative layer for 2D material-based triboelectric nanogenerators: Material modifications and architectural designs",
    authors: "SA Khan, QM Saqib, J Bae, SW Cho",
    venue: "Chemical Engineering Journal 516, 163854",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:HDshCWvjkbEC",
    citations: "22",
  },
  {
    id: "ja-12",
    title: "Neuromorphic devices for electronic skin applications",
    authors: "CS Patil, SB Ghode, J Kim, GU Kamble, SS Kundale, A Mannan, Y Ko, ...",
    venue: "Materials Horizons 12 (7), 2045-2088",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:hFOr9nPyWt4C",
    citations: "55",
  },
  {
    id: "ja-13",
    title: "Plasma-assisted surface engineering of binary metal chalcogenides: a path toward high energy efficiency, electrocatalysts for water splitting, and urea oxidation with stability …",
    authors: "SR Patil, R Kulkarni, SB Ghode, J Kim, QM Saqib, M Noman, CS Patil, ...",
    venue: "ACS Applied Energy Materials 8 (4), 2346-2359",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:-f6ydRqryjwC",
    citations: "18",
  },
  {
    id: "ja-14",
    title: "Multi-layered quasi-2D perovskite based triboelectric nanogenerator",
    authors: "RA Shaukat, M Noman, QM Saqib, A Umair, MM Baig, M Yousuf, ...",
    venue: "Colloids and Surfaces A: Physicochemical and Engineering Aspects 705, 135728",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:IWHjjKOFINEC",
    citations: "8",
  },
  {
    id: "ja-15",
    title: "Arbitrary directional triboelectric nanogenerators: Advanced energy harvesting for sustainable future",
    authors: "QM Saqib, M Yousuf, M Noman, A Mannan, CS Patil, J Kim, SR Patil, Y Ko, ...",
    venue: "Nano Energy 133, 110456",
    year: "2025",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:qUcmZB5y_30C",
    citations: "13",
  },
  {
    id: "ja-16",
    title: "Ti3C2Tx-MXene based 2D/3D Ti3C2–TiO2–CuTiO3 heterostructure for enhanced pseudocapacitive performance",
    authors: "M Noman, MM Baig, QM Saqib, SR Patil, CS Patil, J Kim, Y Ko, E Lee, ...",
    venue: "Chemical Engineering Journal 499, 156697",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:ZeXyd9-uunAC",
    citations: "31",
  },
  {
    id: "ja-17",
    title: "Novel intercalation approach in MXene using modified silica nanospheres to enhance the surface charge density for superior triboelectric performance",
    authors: "MM Baig, QM Saqib, M Noman, M Sheeraz, A Rasheed, M Yousuf, E Lee, ...",
    venue: "Advanced Functional Materials 34 (48), 2408271",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:L8Ckcad2t8MC",
    citations: "37",
  },
  {
    id: "ja-18",
    title: "Synergistic integration of graphene quantum dots into metal–organic framework-5 for enhancing triboelectric nanogenerator performance",
    authors: "CS Patil, QM Saqib, J Kim, M Noman, SR Patil, Y Ko, MD Kurkuri, J Bae",
    venue: "Advanced Composites and Hybrid Materials 7 (5), 154",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:7PzlFSSx8tAC",
    citations: "22",
  },
  {
    id: "ja-19",
    title: "Controlling triboelectric charge of MOFs by leveraging ligands chemistry",
    authors: "M Noman, QM Saqib, S Ameen, SR Patil, CS Patil, J Kim, Y Ko, BS Kim, ...",
    venue: "Advanced Science 11 (35), 2404993",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:dhFuZR0502QC",
    citations: "30",
  },
  {
    id: "ja-20",
    title: "Unveiling the marine Sargassum horneri material for energy and active sensor devices: Towards multitasking approaches",
    authors: "SR Patil, M Noman, R Kulkarni, CS Patil, QM Saqib, MY Chougale, J Kim, ...",
    venue: "Nano Today 57, 102379",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:QIV2ME_5wuYC",
    citations: "22",
  },
  {
    id: "ja-21",
    title: "Miniaturizing power: Harnessing micro-supercapacitors for advanced micro-electronics",
    authors: "QM Saqib, A Mannan, M Noman, MY Chougale, CS Patil, Y Ko, J Kim, ...",
    venue: "Chemical Engineering Journal 490, 151857",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:mVmsd5A6BfQC",
    citations: "51",
  },
  {
    id: "ja-22",
    title: "Triboelectric energy harvesting from highly conjugated fused aromatic ladder structure under extreme environmental conditions",
    authors: "QM Saqib, I Ahmad, A Mannan, J Mahmood, S Ameen, CS Patil, ...",
    venue: "Advanced Materials 36 (19), 2311029",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:4DMP91E08xMC",
    citations: "36",
  },
  {
    id: "ja-23",
    title: "Triboelectric nanogenerator based on coastal bio-waste Ulva lactuca from Jeju Island for sustainable energy harvesting",
    authors: "M Noman, RA Shaukat, SR Patil, MY Chougale, J Kim, CS Patil, ...",
    venue: "Journal of Science: Advanced Materials and Devices 9 (1), 100669",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:aqlVkmm33-oC",
    citations: "15",
  },
  {
    id: "ja-24",
    title: "Triboelectric nanogenerator based on reactivated electrode materials derived from waste alkaline battery: Influence of pyrolysis temperature and surface morphology",
    authors: "CS Patil, QM Saqib, SR Patil, M Noman, MY Chougale, RA Shaukat, ...",
    venue: "Nano Energy 121, 109205",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:qxL8FJ1GzNcC",
    citations: "23",
  },
  {
    id: "ja-25",
    title: "Nature‐driven edible black soldier fly (BSF) insect larvae derived chitin biofilm for sustainable multifunctional energy harvesting",
    authors: "SR Patil, MY Chougale, J Kim, RA Shaukat, M Noman, QM Saqib, ...",
    venue: "Advanced Sustainable Systems 8 (2), 2300312",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:M3ejUd6NZC8C",
    citations: "13",
  },
  {
    id: "ja-26",
    title: "F8BT-based highly sensitive humidity sensor for metaverse interfacing",
    authors: "J Kim, MY Chougale, RA Shaukat, SR Patil, M Noman, CS Patil, ...",
    venue: "Sensors and Actuators B: Chemical 398, 134717",
    year: "2024",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:YOwf2qJgpHMC",
    citations: "8",
  },
  {
    id: "ja-27",
    title: "Sea urchin shaped hierarchical cobalt carbonate hydroxide hydrate-PANI nanocomposite with enhanced redox activity for asymmetric supercapacitor",
    authors: "M Noman, RA Shaukat, QM Saqib, MY Chougale, J Kim, SR Patil, ...",
    venue: "Journal of Energy Storage 73, 109259",
    year: "2023",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:_kc_bZDykSQC",
    citations: "19",
  },
  {
    id: "ja-28",
    title: "Organic semiconductor polymers: a carbazole-based novel tribopositive polymer for energy harvesting with high temperature stability",
    authors: "RA Shaukat, S Ameen, QM Saqib, MY Chougale, J Kim, SR Patil, ...",
    venue: "Journal of Materials Chemistry A 11 (27), 14800-14808",
    year: "2023",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:ULOm3_A8WrAC",
    citations: "13",
  },
  {
    id: "ja-29",
    title: "Snake ecdysis: A potential e-material for advanced electronic technology",
    authors: "MY Chougale, MU Khan, J Kim, J Cosgrove, RA Shaukat, QM Saqib, ...",
    venue: "Nano Energy 111, 108399",
    year: "2023",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:KlAtU1dfN6UC",
    citations: "27",
  },
  {
    id: "ja-30",
    title: "Advancement in soft iontronic resistive memory devices and their application for neuromorphic computing",
    authors: "MU Khan, J Kim, MY Chougale, RA Shaukat, QM Saqib, SR Patil, ...",
    venue: "Advanced Intelligent Systems 5 (2), 2200281",
    year: "2023",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:kNdYIx-mwKoC",
    citations: "42",
  },
  {
    id: "ja-31",
    title: "Triboelectric Nanogenerator Based on Biowaste Tribopositive Delonix Regia Flowers Powder",
    authors: "SR Patil, MY Chougale, J Kim, RA Shaukat, M Noman, QM Saqib, ...",
    venue: "Energy Technology 10 (12), 2200876",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:MXK_kJrjxJIC",
    citations: "32",
  },
  {
    id: "ja-32",
    title: "Highly flexible and asymmetric hexagonal‐shaped crystalline structured germanium dioxide‐based multistate resistive switching memory device for data storage and neuromorphic …",
    authors: "MY Chougale, MU Khan, J Kim, CM Furqan, QM Saqib, RA Shaukat, ...",
    venue: "Advanced Electronic Materials 8 (10), 2200332",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:8k81kl-MbHgC",
    citations: "23",
  },
  {
    id: "ja-33",
    title: "Bioinspired soft multistate resistive memory device based on silk fibroin gel for neuromorphic computing",
    authors: "MY Chougale, MU Khan, J Kim, RA Shaukat, QM Saqib, SR Patil, ...",
    venue: "Advanced Engineering Materials 24 (10), 2200314",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:hqOjcs7Dif8C",
    citations: "27",
  },
  {
    id: "ja-34",
    title: "Particle triboelectric nanogenerator (P-TENG)",
    authors: "QM Saqib, RA Shaukat, MY Chougale, MU Khan, J Kim, J Bae",
    venue: "Nano Energy 100, 107475",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:5nxA0vEk-isC",
    citations: "39",
  },
  {
    id: "ja-35",
    title: "Triboelectric nanogenerator based on lignocellulosic waste fruit shell tribopositive material: Comparative analysis",
    authors: "QM Saqib, MY Chougale, MU Khan, RA Shaukat, J Kim, KS Bhat, J Bae",
    venue: "Materials Today Sustainability 18, 100146",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:UebtZRa9Y70C",
    citations: "73",
  },
  {
    id: "ja-36",
    title: "Ultra-robust tribo-and piezo-electric nanogenerator based on metal organic frameworks (MOF-5) with high environmental stability",
    authors: "RA Shaukat, QM Saqib, J Kim, H Song, MU Khan, MY Chougale, J Bae, ...",
    venue: "Nano Energy 96, 107128",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:Se3iqnhoufwC",
    citations: "147",
  },
  {
    id: "ja-37",
    title: "Ionic liquid multistate resistive switching characteristics in two terminal soft and flexible discrete channels for neuromorphic computing",
    authors: "MU Khan, J Kim, MY Chougale, CM Furqan, QM Saqib, RA Shaukat, ...",
    venue: "Microsystems & Nanoengineering 8 (1), 56",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:0EnyYjriUFMC",
    citations: "36",
  },
  {
    id: "ja-38",
    title: "Two dimensional Zirconium diselenide based humidity sensor for flexible electronics",
    authors: "RA Shaukat, MU Khan, QM Saqib, MY Chougale, J Kim, A Bermak, J Bae",
    venue: "Sensors and Actuators B: Chemical 358, 131507",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:roLk4NBRz8UC",
    citations: "75",
  },
  {
    id: "ja-39",
    title: "Asymmetric GaN/ZnO engineered resistive memory device for electronic synapses",
    authors: "MU Khan, CM Furqan, J Kim, SA Khan, QM Saqib, MY Chougale, ...",
    venue: "ACS Applied Electronic Materials 4 (1), 297-307",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:LkGwnXOMwfcC",
    citations: "30",
  },
  {
    id: "ja-40",
    title: "Expired pharmaceutical drugs as tribopositive material for triboelectric nanogenerator",
    authors: "MY Chougale, QM Saqib, MU Khan, RA Shaukat, J Kim, D Dubal, J Bae",
    venue: "Advanced Sustainable Systems 5 (12), 2100205",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:ufrVoPGSRksC",
    citations: "34",
  },
  {
    id: "ja-41",
    title: "Natural seagrass tribopositive material based spray coatable triboelectric nanogenerator",
    authors: "QM Saqib, MY Chougale, MU Khan, RA Shaukat, J Kim, J Bae, HW Lee, ...",
    venue: "Nano Energy 89, 106458",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:zYLM7Y9cAGgC",
    citations: "79",
  },
  {
    id: "ja-42",
    title: "Bio-waste sunflower husks powder based recycled triboelectric nanogenerator for energy harvesting",
    authors: "RA Shaukat, QM Saqib, MU Khan, MY Chougale, J Bae",
    venue: "Energy Reports 7, 724-731",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:d1gkVwhDpl0C",
    citations: "118",
  },
  {
    id: "ja-43",
    title: "All range highly linear and sensitive humidity sensor based on 2D material TiSi2 for real-time monitoring",
    authors: "RA Shaukat, MU Khan, QM Saqib, MY Chougale, J Kim, J Bae",
    venue: "Sensors and Actuators B: Chemical 345, 130371",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:Y0pCki6q_DkC",
    citations: "85",
  },
  {
    id: "ja-44",
    title: "Soft and flexible: core-shell ionic liquid resistive memory for electronic synapses",
    authors: "MU Khan, QM Saqib, MY Chougale, RA Shaukat, J Kim, J Bae",
    venue: "Microsystems & nanoengineering 7 (1), 78",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:WF5omc3nYNoC",
    citations: "32",
  },
  {
    id: "ja-45",
    title: "Novel recycled triboelectric nanogenerator based on polymer‐coated trash soda can for clean energy harvesting",
    authors: "MY Chougale, QM Saqib, MU Khan, RA Shaukat, J Kim, J Bae",
    venue: "Advanced Sustainable Systems 5 (10), 2100161",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:UeHWp8X0CEIC",
    citations: "47",
  },
  {
    id: "ja-46",
    title: "Wide range and highly linear signal processed systematic humidity sensor array using Methylene Blue and Graphene composite",
    authors: "MU Khan, G Hassan, RA Shaukat, QM Saqib, MY Chougale, J Kim, J Bae",
    venue: "Scientific reports 11 (1), 16665",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:Tyk-4Ss8FVUC",
    citations: "19",
  },
  {
    id: "ja-47",
    title: "Natural hierarchically structured highly porous tomato peel based tribo‐and piezo‐electric nanogenerator for efficient energy harvesting",
    authors: "QM Saqib, MU Khan, H Song, MY Chougale, RA Shaukat, J Kim, J Bae, ...",
    venue: "Advanced Sustainable Systems 5 (7), 2100066",
    year: "2021",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:YsMSGLbcyi4C",
    citations: "50",
  },
  {
    id: "ja-48",
    title: "Biowaste peanut shell powder-based triboelectric nanogenerator for biomechanical energy scavenging and sustainably powering electronic supplies",
    authors: "QM Saqib, RA Shaukat, MU Khan, M Chougale, J Bae",
    venue: "ACS Applied Electronic Materials 2 (12), 3953-3963",
    year: "2020",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:9yKSN-GCB0IC",
    citations: "81",
  },
  {
    id: "ja-49",
    title: "Inner egg shell membrane based bio-compatible capacitive and piezoelectric function dominant self-powered pressure sensor array for smart electronic applications",
    authors: "QM Saqib, MU Khan, J Bae",
    venue: "RSC advances 10 (49), 29214-29227",
    year: "2020",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:eQOLeE2rZwMC",
    citations: "31",
  },
  {
    id: "ja-50",
    title: "All printed organic humidity sensor based on egg albumin",
    authors: "MU Khan, QM Saqib, G Hassan, J Bae",
    venue: "Sensing and Bio-Sensing Research 28, 100337",
    year: "2020",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=3U5h4AoAAAAJ:IjCSPb-OGe4C",
    citations: "33",
  }
];

export const conferencePapers: Publication[] = [
  {
    id: "cp-01",
    title: "Egg Albumin based Highly Sensitive Humidity Sensor",
    authors: "MU Khan, QM Saqib, J Bae",
    venue: "2019 2nd International Conference on Electrical, Communication and Computer Engineering (ICECE)",
    year: "2019",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ",
  },
  {
    id: "cp-02",
    title: "A review on non-volatile resistive switching memory based on 2D materials",
    authors: "QM Saqib, MU Khan, J Bae",
    venue: "2020 International Conference on Applied and Robotics Engineering (ICARES)",
    year: "2020",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ",
  }
];

export const patents: Publication[] = [
  {
    id: "pat-01",
    title: "Energy harvesting device using Delonix regia powder, and manufacturing method thereof",
    authors: "J Bae, SR Patil, QM Saqib, MY Chougale, J Kim",
    venue: "Korean Intellectual Property Office (KIPO)",
    year: "2022",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ",
    patentNumber: "10-2022-0144949",
  }
];

export const books: Publication[] = [
  {
    id: "bk-01",
    title: "Polyoxometalate-based materials for sensor systems",
    authors: "QM Saqib, M Noman, J Kim, CS Patil, SR Patil, Y Ko, J Bae",
    venue: "Polyoxometalate-Based Materials and Applications, Elsevier, pp. 263-292",
    year: "2026",
    doi: "10.1016/B978-0-443-18955-5.00010-0",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&citation_for_view=3U5h4AoAAAAJ:kNdYIx-mwKoC",
  },
  {
    id: "bk-02",
    title: "Resistive Switching-based Neuromorphic Devices for Artificial Neural Networks",
    authors: "MY Chougale, RA Shaukat, SR Patil, M Noman, J Kim, QM Saqib, J Bae",
    venue: "Functional Materials and Devices, Royal Society of Chemistry (RSC)",
    year: "2023",
    doi: "10.1039/9781837670659-00249",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&citation_for_view=3U5h4AoAAAAJ:0EnyYjriUFMC",
  },
  {
    id: "bk-03",
    title: "Polymer Nanocomposites for Resistive Switching Memory",
    authors: "QM Saqib, MU Khan, J Bae",
    venue: "Polymer Nanocomposite Materials: Applications in Integrated Electronic Devices, Wiley",
    year: "2021",
    doi: "10.1002/9783527830756.ch7",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=3U5h4AoAAAAJ&citation_for_view=3U5h4AoAAAAJ:YsMSGLbcyi4C",
  }
];
